language: java

jdk:
  - oraclejdk8

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

after_success:
- mvn clean cobertura:cobertura coveralls:report

# see: http://docs.travis-ci.com/user/migrating-from-legacy/?utm_source=legacy-notice&utm_medium=banner&utm_campaign=legacy-upgrade
sudo: false

before_deploy: "mvn -DskipTests package -Pgtk_linux_i386,-gtk_linux_amd64"

deploy:
  provider: releases
  api_key: "fe538f3e62783dbf4bc5c9347432057619bfa124"
  file: "marabou-*-linux-gtk-x86"
  skip_cleanup: true
  on:
    tags: true
