version: '{build}'

skip_tags: true

clone_depth: 5

install:
  - choco install openjdk11
  - choco install maven
  - refreshenv

build_script:
  - mvn clean verify

cache:
  - C:\maven\
  - C:\Users\appveyor\.m2
