version: '{build}'

skip_tags: true

clone_depth: 5

os: Windows Server 2012

#environment:
#JAVA_HOME: C:\Program Files\Java\jdk1.8.0

install:
  - choco install jdk8
  - choco install maven
  - refreshenv

build_script:
  - mvn clean verify

cache:
  - C:\maven\
  - C:\Users\appveyor\.m2
