version: '{build}'
skip_tags: true
clone_depth: 5
environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
os: Windows Server 2012
install: choco install maven
build_script:
  - mvn clean verify
cache:
  - C:\maven\
  - C:\Users\appveyor\.m2
